name: Deploy NodeJS Application

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker-HUB
        if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$


      - name: Build and Run doocker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

        
